### PR TITLE
Enable building custom LCM types

### LINKED ISSUE #15: Custom LCM types for robot plans.
At the moment we're relying on drake's `lcmt_robot_plan` to encode plans. `lcmt_robot_plan` seems to have been designed for joint space plans only, and we're forced to write plan type information in the string fields of `lcmt_robot_state`, another lcm type that comes with drake. 

Based on preliminary discussions on Slack, here's the new proposed lcm type for robot plans:
```
struct lcmt_our_robot_plan
{
  enum plan_type; // kJointSpacePlan, kTaskSpacePlan, etc...
  int_32_t num_joint_space_plans;
  lcmt_joint_space_plan joint_space_plans[num_joint_space_plans];
  int32_t num_task_space_plans;
  lcmt_task_space_plan task_space_plans[num_task_space_plans];
  // other num_plan, vector<Plan> pairs. 
}
```
Here `joint_space_plans ` and `task_space_plans ` are also custom lcm types.

### PR DESCRIPTION
**Pull request by mpetersen94**
This starts putting together the piping to build our own lcmtypes.  I have not yet created the lcmtypes we've talked about and am still working on getting the built lcmtypes imported elsewhere in our code.

Also I renamed `robot_plan_runner` to `robot-plan-runner` to match the repo name.

Closes #15 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/20)

### CODE REVIEW

**Comment by hjsuh94** [comment]
One question about building our own lcm types - does this also build the python lcm bindings for us so that we can use the type in our client? 

Perhaps we could include some example code in this PR to confirm that the built types are working correctly?

**Comment by mpetersen94** [comment]
It does build the python types as well.  If you do the usual cmake/make -j process and look under `build/lcmtypes/robot-plan-runner` you should see both the c++ and python lcmtypes.  I have not yet been able to get examples working.  For python, I'm pretty sure I just need it on the python path but for C++ I can't figure out the cmake.  And advice would be helpful.  Can push up what I've tried if that helps.

**Comment by mpetersen94** [comment]
@pangtao22 Here is the PR I was talking about.  It currently builds the lcm messages in the lcmtypes using cmake (placed in `build/lcmtypes/robot_plan_runner`.  If you put `build\lcmtypes` on the PYTHON_PATH, the lcmtypes can be found and used just fine (see example).  However, I can't figure out how to get a C++ example to build with the custom LCM types.  If you could take a look that would be great.  I took a stab in the sandbox file.

**Comment by pangtao22** [comment]
@mpetersen94 I came up with an ugly solution that installs the lcm-types locally and makes the CI happy for now. I think eventually we'll want our lcm types to be a standalone package, similar to how drake deals with its lcm types.

**Review by mpetersen94 — COMMENTED** [review]
Thanks for getting this working.  I'm assuming right now you have to build the lcmtypes and then build the rest of the repo right?  I'm going to play with it a little more to make that workflow easier if I can.

> Reviewed 7 of 8 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/20#-:-MZIy_4R5chaZfYMo9rp:bt97lk3)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @hjsuh94, @mpetersen94, and @pangtao22)

___
*[lcmtypes/CMakeLists.txt, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/20#-MZJ-4Pm0n0ce8rYgl3y:-MZJ-4Pm0n0ce8rYgl3z:bcrf57e) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/ae3ae750d81245716165e8b56ab6f4524875d563/lcmtypes/CMakeLists.txt#L14)):*
> ```CMake
> lcm_install_python(${python_sources})
> 
> add_custom_target(GenHeaders ALL
> ```

I'm going to put this back in so you don't have to make the .source file separately.
___
*[lcmtypes/CMakeLists.txt, line 3 at r3](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/20#-MZIy0BDDWUO4U2dOXQa:-MZIy0BDDWUO4U2dOXQb:bx3q66z) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/c1702bb5650402682bb60f142702dae30de4df58/lcmtypes/CMakeLists.txt#L3)):*
> ```CMake
> cmake_minimum_required(VERSION 3.10.2)
> project(robot-plan-runner-lcm-types)
> ```

I'm going to make this `robot-plan-runner-lcmtypes` for consistency

**Review by mpetersen94 — COMMENTED** [review]
I made some changes to the cmake architecture so that you no longer need to build the lcmtypes separately.  Building at the top level as described in the Readme will build the lcmtypes and the plan runner, linking everything up nicely.  PTAL.

> Reviewed 1 of 1 files at r4, 7 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/20#-:-MZJ7SUg2EBlnnjl31z-:bgot2dl)* status: 8 of 10 files reviewed, all discussions resolved (waiting on @hjsuh94 and @pangtao22)

**Review by mpetersen94 — COMMENTED** [review]
I think I can throw them in super quick while I'm here and have the lcm docs pulled up.  Let me try that.

> Reviewed 2 of 7 files at r1, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/20#-:-MZJCE2UB2l_3pyhhASq:bnbvrvt)* status: all files reviewed, 1 unresolved discussion (waiting on @hjsuh94)

___
*[lcmtypes/CMakeLists.txt, line 15 at r5](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/20#-MZJC72tCdZiLJAkRE3k:-MZJBnAY3zI7kA0XVbYc:bo7rnzf) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/98eefb53cf12c082d72feec354078cb62c33174e/lcmtypes/CMakeLists.txt#L15)):*
> ```CMake
> lcm_add_library(${PROJECT_NAME} CPP ${lcm_cpp_headers})
> lcm_install_headers(DESTINATION ${CMAKE_CURRENT_SOURCE_DIR} ${lcm_cpp_headers})
> lcm_install_python(DESTINATION ${CMAKE_CURRENT_SOURCE_DIR} ${lcm_python_sources})
> ```

I would like to leave these in so that downstream projects can install them as needed.

**Review by hjsuh94 — APPROVED** [review]
:lgtm: for me - everything seems to be working good! 

One minor comment, but maybe it's worth trying to run an import test for plan_runners' lcm types in `import_all_test.py`?

That way we can warn users at build time about path issues. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/20#-:-MZJDV-IAontCOw0eMUR:bv2r4sy)* status: all files reviewed, 1 unresolved discussion (waiting on @mpetersen94)

**Review by pangtao22 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/20)* status: all files reviewed, 1 unresolved discussion (waiting on @mpetersen94)

___
*[lcmtypes/CMakeLists.txt, line 15 at r5](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/20#-MZJC72tCdZiLJAkRE3k:-MZJFHWK3MCLysIe1r4D:b-ja6rqa) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/98eefb53cf12c082d72feec354078cb62c33174e/lcmtypes/CMakeLists.txt#L15)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

I would like to leave these in so that downstream projects can install them as needed.
</blockquote></details>

Sure! But eventually it might be better to have a cpp package for cpp headers, and a python site-package for the python types? That seems to be what drake does, but it's probably too strong a dose of cmake for one PR :D

**Review by mpetersen94 — COMMENTED** [review]
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mpetersen94)

___
*[lcmtypes/CMakeLists.txt, line 15 at r5](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/20#-MZJC72tCdZiLJAkRE3k:-MZJI9uh5LCY6I0lQ88j:bqpaect) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/98eefb53cf12c082d72feec354078cb62c33174e/lcmtypes/CMakeLists.txt#L15)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

Sure! But eventually it might be better to have a cpp package for cpp headers, and a python site-package for the python types? That seems to be what drake does, but it's probably too strong a dose of cmake for one PR :D
</blockquote></details>


That's a good point.  I'll leave it as is!

**Review by mpetersen94 — COMMENTED** [review]
Great idea Terry. Added!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/20#-:-MZJRV_dBNul3owPayp_:b-spdzdi)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mpetersen94)

**Review by pangtao22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/20)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @mpetersen94)

___
*[scripts/build_test.sh, line 8 at r8](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/20#-MZJTV07AThdQ2xSZfTQ:-MZJTV089kQKI1MkCGJi:bbqmviw) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/ce9e5f51acc09f6a141d3838125fefc8c482155c/scripts/build_test.sh#L8)):*
> ```Shell
> cmake -DCMAKE_PREFIX_PATH=/opt/drake  /github/workspace
> make -j
> export PYTHON_PATH=/robot-plan-runner-build/robot-plan-runner-lcmtypes
> ```

Or `export PYTHONPATH=${PYTHONPATH}:/robot-plan-runner-build/robot-plan-runner-lcmtypes`? $PYTHONPATH$ is also the environment variable for pydrake.

**Review by mpetersen94 — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mpetersen94)

___
*[scripts/build_test.sh, line 8 at r8](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/20#-MZJTV07AThdQ2xSZfTQ:-MZJUW_LEoU5njzdspPY:b-evwuqn) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/ce9e5f51acc09f6a141d3838125fefc8c482155c/scripts/build_test.sh#L8)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

Or `export PYTHONPATH=${PYTHONPATH}:/robot-plan-runner-build/robot-plan-runner-lcmtypes`? $PYTHONPATH$ is also the environment variable for pydrake. 
</blockquote></details>

Yep! Just figured out that bug.  Done.

**Review by mpetersen94 — COMMENTED** [review]
> Reviewed 1 of 8 files at r11, 5 of 7 files at r12, 1 of 1 files at r13, 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mpetersen94)

**Review by mpetersen94 — COMMENTED** [review]
> Reviewed 2 of 2 files at r15.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mpetersen94)

**Comment by mpetersen94** [comment]
Finally passes CI.  Merging.

**Pull request merged**
