### PR TITLE
Wrap StateMachine in a drake system.

### PR DESCRIPTION
**Pull request by pangtao22**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10)

### CODE REVIEW

**Review by pangtao22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @pangtao22)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYkdILL62p8cNi0_NTN:-MYkdILL62p8cNi0_NTO:bpyywmd) (no related file):*
Summary:
1. A `LeafSystem` version of `IiwaPlanManager`, named `IiwaPlanManagerSystem`.
2. Similar to `IiwaPlanManager`, it owns a `IiwaPlanFactory` and a `PlanManagerStateMachine`.
2. Unlike `IiwaPlanManager`, which has separate threads for (1) receiving plans, (2) printing status and (3) computing Iiwa commands, `IiwaPlanManagerSystem`has these events scheduled by drake's `Simulator`.
3. To receive plans, `IiwaPlanManagerSystem` subscribes to channel `ROBOT_PLAN` for messages of type `lcmt_robot_plan`. This is different from the zmq-based server-client setup in `IiwaPlanManager`. Notably, the client is not blocked while the server is executing the plan. This can be changed by making the client to wait for a success signal from a `ROBOT_PLAN_STATUS` channel, but that will need to wait until we support our own lcm types.
4. As mentioned in the comments, the update rate of `IiwaPlanManagerSystem`is driven by its downstream system. In a simulation-only diagram without lcm publishing/subscription, an abstract-valued `ZeroOrderHold` is needed to set the rate at which `lcmt_iiwa_command` is computed.

---

**Review by pangtao22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @hjsuh94 and @mpetersen94)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYkdILL62p8cNi0_NTN:-MYkyFDp6BTFR5tWtp0n:b1kbcnd) (no related file):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

Summary:
1. A `LeafSystem` version of `IiwaPlanManager`, named `IiwaPlanManagerSystem`.
2. Similar to `IiwaPlanManager`, it owns a `IiwaPlanFactory` and a `PlanManagerStateMachine`.
2. Unlike `IiwaPlanManager`, which has separate threads for (1) receiving plans, (2) printing status and (3) computing Iiwa commands, `IiwaPlanManagerSystem`has these events scheduled by drake's `Simulator`.
3. To receive plans, `IiwaPlanManagerSystem` subscribes to channel `ROBOT_PLAN` for messages of type `lcmt_robot_plan`. This is different from the zmq-based server-client setup in `IiwaPlanManager`. Notably, the client is not blocked while the server is executing the plan. This can be changed by making the client to wait for a success signal from a `ROBOT_PLAN_STATUS` channel, but that will need to wait until we support our own lcm types.
4. As mentioned in the comments, the update rate of `IiwaPlanManagerSystem`is driven by its downstream system. In a simulation-only diagram without lcm publishing/subscription, an abstract-valued `ZeroOrderHold` is needed to set the rate at which `lcmt_iiwa_command` is computed.


</blockquote></details>

+@hjsuh94 +@mpetersen94  for review. 

---

**Review by pangtao22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @hjsuh94 and @mpetersen94)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYkdILL62p8cNi0_NTN:-MYl-iKA03XSoXQmkIpU:bqe5n2g) (no related file):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

+@hjsuh94 +@mpetersen94  for review. 
</blockquote></details>

Changes made to `PlanManagerStateMachine`:
1. As drake simulator stores time as doubles, time points are now stored as doubles in seconds instead of `std::chrono::time_point`. Methods that take `time_point` are preserved and delegated to methods that take doubles.
2. In state IDLE, iiwa_commands are being sent at 200Hz instead of sending no commands. This is because drake's `IiwaCommandReceiver` needs a valid (num_joints == 7) command message. This idle command message is computed as follows:
- position is the `Iiwa_position_measured`field of the `lcmt_iiwa_status` message when state transitions into IDLE. 
- torque is 0.

---

**Review by mpetersen94 — CHANGES_REQUESTED** [review]
> Reviewed 21 of 24 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10)* status: all files reviewed, 6 unresolved discussions (waiting on @hjsuh94 and @pangtao22)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYkdILL62p8cNi0_NTN:-MYlDelOAI9F_eADQYgw:b45u8gf) (no related file):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

Changes made to `PlanManagerStateMachine`:
1. As drake simulator stores time as doubles, time points are now stored as doubles in seconds instead of `std::chrono::time_point`. Methods that take `time_point` are preserved and delegated to methods that take doubles.
2. In state IDLE, iiwa_commands are being sent at 200Hz instead of sending no commands. This is because drake's `IiwaCommandReceiver` needs a valid (num_joints == 7) command message. This idle command message is computed as follows:
- position is the `Iiwa_position_measured`field of the `lcmt_iiwa_status` message when state transitions into IDLE. 
- torque is 0.
</blockquote></details>

Do we want to set the idle command to be the last measured position before transitioning to idle or the last commanded position before transitioning to idle?

---
___
*[src/plan_runner/iiwa_plan_manager.cc, line 56 at r2](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYlCl9b2L0dvqAsY-nc:-MYlCl9b2L0dvqAsY-nd:b-l91108) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/fdc722c76b21a3a74105bc8321ec83ae782d6ad1/src/plan_runner/iiwa_plan_manager.cc#L56)):*
> ```cpp
>   using namespace std::chrono_literals;
>   while (true) {
>     std::this_thread::sleep_for(1000ms);
> ```

What's the difference?
___
*[src/plan_runner/plan_manager_system/iiwa_plan_manager_system.h, line 50 at r2](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYl7xPD835jYbBRKTrU:-MYl7xPD835jYbBRKTrV:b-3zslud) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/fdc722c76b21a3a74105bc8321ec83ae782d6ad1/src/plan_runner/plan_manager_system/iiwa_plan_manager_system.h#L50)):*
> ```objc
> 
>   // a constant reference to the MBP in plan_factory_.
>   const drake::multibody::MultibodyPlant<double> &plant_;
> ```

Is this ever used from this class?  Plan factory obviously needs it but does this class?
___
*[src/plan_runner/plan_manager_system/iiwa_plan_manager_system.cc, line 23 at r2](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYl0PJJDIWKed1Go_BY:-MYl0PJK1HTjhFRGc9L5:bo52loq) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/fdc722c76b21a3a74105bc8321ec83ae782d6ad1/src/plan_runner/plan_manager_system/iiwa_plan_manager_system.cc#L23)):*
> ```cpp
>   //  only printing is done in that event, therefore this state is not updated.
>   DeclareDiscreteState(1);
>   DeclarePeriodicDiscreteUpdateEvent(
> ```

Should this be a periodic publish event instead of a discrete update event since nothing is getting updated? That would let you get rid of the discrete state.
___
*[src/plan_runner/plan_manager_system/iiwa_plan_manager_system.cc, line 96 at r2](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYl6lLOEEQwI5zh2imO:-MYl6lLOEEQwI5zh2imP:beeahts) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/fdc722c76b21a3a74105bc8321ec83ae782d6ad1/src/plan_runner/plan_manager_system/iiwa_plan_manager_system.cc#L96)):*
> ```cpp
>     // Behavior with mock_station_simulation:
>     //  throws with error message:
>     //   IiwaCommandReceiver expected num_joints = 7, but received 0.
> ```

I don't love the idea that if a bad command is sent in, all systems crash.  Looking back at Spartan, when a plan gives a bad command, the plan is stopped with status "STOPPED_BY_SAFETY_CHECK" and the last command is sent to the robot (transitioning to state Idle).  Would that be a better workflow?
___
*[src/plan_runner/plan_manager_system/iiwa_plan_manager_system.cc, line 107 at r2](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYl7gwsEW9wARnhbWF7:-MYl7gwsEW9wARnhbWF8:b-yt3tf) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/fdc722c76b21a3a74105bc8321ec83ae782d6ad1/src/plan_runner/plan_manager_system/iiwa_plan_manager_system.cc#L107)):*
> ```cpp
> 
>   // Check command for error.
>   if (!state_machine_->CommandHasError(s, c)) {
> ```

What happens if there is an error?
___
*[src/plan_runner/state_machine/plan_manager_state_machine.h, line 18 at r2](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYlAuhkAjfWXc-Fn_-y:-MYlAuhkAjfWXc-Fn_-z:bb3xdny) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/fdc722c76b21a3a74105bc8321ec83ae782d6ad1/src/plan_runner/state_machine/plan_manager_state_machine.h#L18)):*
> ```objc
>   kStateError
> };
> using TimePoint = std::chrono::time_point<std::chrono::high_resolution_clock>;
> ```

Are either of these still useful or can we just use double across all instances of time?
___
*[src/plan_runner/state_machine/plan_manager_state_machine.cc, line 37 at r2](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYl8Hk76Z2ItX4DK7NF:-MYl8Hk80h0OXCuQovnx:b2m3699) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/fdc722c76b21a3a74105bc8321ec83ae782d6ad1/src/plan_runner/state_machine/plan_manager_state_machine.cc#L37)):*
> ```cpp
> }
> 
> bool PlanManagerStateBase::CommandHasError(const State & state,
> ```

I appreciate moving the error checking to one place.

**Review by pangtao22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10)* status: all files reviewed, 6 unresolved discussions (waiting on @hjsuh94 and @mpetersen94)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYkdILL62p8cNi0_NTN:-MYlG3is6m2FC_PYw58y:b-11i700) (no related file):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Do we want to set the idle command to be the last measured position before transitioning to idle or the last commanded position before transitioning to idle?
</blockquote></details>

The one I've been using is the last measured position, but I'm not sure if that's the best choice. We'll need to find out on the robots!

---
___
*[src/plan_runner/iiwa_plan_manager.cc, line 56 at r2](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYlCl9b2L0dvqAsY-nc:-MYlGMbS0hjPFItOncgu:b-ywjw23) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/fdc722c76b21a3a74105bc8321ec83ae782d6ad1/src/plan_runner/iiwa_plan_manager.cc#L56)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

What's the difference?
</blockquote></details>

I found that `std::this_thread::sleep_for` is not accurate (off by a couple milliseconds every time), so I was wondering if it's because I was specifying the duration in seconds. And it turns out that using `ms` doesn't make `sleep_for` more accurate. 
___
*[src/plan_runner/plan_manager_system/iiwa_plan_manager_system.h, line 50 at r2](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYl7xPD835jYbBRKTrU:-MYlIjiW4dB0GUYWZ9Vn:b-42g4dz) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/fdc722c76b21a3a74105bc8321ec83ae782d6ad1/src/plan_runner/plan_manager_system/iiwa_plan_manager_system.h#L50)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Is this ever used from this class?  Plan factory obviously needs it but does this class?
</blockquote></details>

It's not used in this class and I can't remember why I added it... will remove. 
___
*[src/plan_runner/plan_manager_system/iiwa_plan_manager_system.cc, line 23 at r2](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYl0PJJDIWKed1Go_BY:-MYlGyhWD1w23YqjpJfw:b-70rric) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/fdc722c76b21a3a74105bc8321ec83ae782d6ad1/src/plan_runner/plan_manager_system/iiwa_plan_manager_system.cc#L23)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Should this be a periodic publish event instead of a discrete update event since nothing is getting updated? That would let you get rid of the discrete state.
</blockquote></details>

Nice catch! 
___
*[src/plan_runner/plan_manager_system/iiwa_plan_manager_system.cc, line 96 at r2](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYl6lLOEEQwI5zh2imO:-MYlHR7E6J1wH1vg04_m:bgec5sd) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/fdc722c76b21a3a74105bc8321ec83ae782d6ad1/src/plan_runner/plan_manager_system/iiwa_plan_manager_system.cc#L96)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

I don't love the idea that if a bad command is sent in, all systems crash.  Looking back at Spartan, when a plan gives a bad command, the plan is stopped with status "STOPPED_BY_SAFETY_CHECK" and the last command is sent to the robot (transitioning to state Idle).  Would that be a better workflow?
</blockquote></details>

I like the idea of handling bad commands more gracefully, but that requires changing the state transition diagram of the state machine, which is not within the scope of this PR. Could you create an issue so that we can solve this in a future PR?
___
*[src/plan_runner/plan_manager_system/iiwa_plan_manager_system.cc, line 107 at r2](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYl7gwsEW9wARnhbWF7:-MYlH8Sq5peNVh-7rkS6:b-m1coxi) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/fdc722c76b21a3a74105bc8321ec83ae782d6ad1/src/plan_runner/plan_manager_system/iiwa_plan_manager_system.cc#L107)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

What happens if there is an error?
</blockquote></details>

State is transitioned to `Error` inside `CommandHasError`. And the next command being sent will be an empty one.
___
*[src/plan_runner/state_machine/plan_manager_state_machine.h, line 18 at r2](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYlAuhkAjfWXc-Fn_-y:-MYlHioXEmvjBAYWsl4A:b-9wxvxr) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/fdc722c76b21a3a74105bc8321ec83ae782d6ad1/src/plan_runner/state_machine/plan_manager_state_machine.h#L18)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Are either of these still useful or can we just use double across all instances of time?
</blockquote></details>

In the multi-threaded version of PlanManager, we still need to convert system clock time points into doubles, and that's where these shorthand types become useful.

**Review by mpetersen94 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10)* status: all files reviewed, 3 unresolved discussions (waiting on @hjsuh94, @mpetersen94, and @pangtao22)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYkdILL62p8cNi0_NTN:-MYlJGhGE9_9D7vc6gtt:b-4k8hmc) (no related file):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

The one I've been using is the last measured position, but I'm not sure if that's the best choice. We'll need to find out on the robots!
</blockquote></details>

Fair answer!

---
___
*[src/plan_runner/plan_manager_system/iiwa_plan_manager_system.cc, line 96 at r2](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYl6lLOEEQwI5zh2imO:-MYlJZpvBozR_rxGbUfQ:bhy9ot6) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/fdc722c76b21a3a74105bc8321ec83ae782d6ad1/src/plan_runner/plan_manager_system/iiwa_plan_manager_system.cc#L96)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

I like the idea of handling bad commands more gracefully, but that requires changing the state transition diagram of the state machine, which is not within the scope of this PR. Could you create an issue so that we can solve this in a future PR?
</blockquote></details>

Will do.
___
*[src/plan_runner/plan_manager_system/iiwa_plan_manager_system.cc, line 107 at r2](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYl7gwsEW9wARnhbWF7:-MYlJd1UBClJ-wMvf7xu:b-f5hj8u) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/fdc722c76b21a3a74105bc8321ec83ae782d6ad1/src/plan_runner/plan_manager_system/iiwa_plan_manager_system.cc#L107)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

State is transitioned to `Error` inside `CommandHasError`. And the next command being sent will be an empty one.
</blockquote></details>

Does that mean no command is sent this time?

**Review by pangtao22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10)* status: 21 of 24 files reviewed, 3 unresolved discussions (waiting on @hjsuh94 and @mpetersen94)

___
*[src/plan_runner/plan_manager_system/iiwa_plan_manager_system.cc, line 107 at r2](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYl7gwsEW9wARnhbWF7:-MYlL10v2uHckrMI5y1a:b-ngjp05) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/fdc722c76b21a3a74105bc8321ec83ae782d6ad1/src/plan_runner/plan_manager_system/iiwa_plan_manager_system.cc#L107)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Does that mean no command is sent this time?
</blockquote></details>

No. The downstream `LcmPublisherSystem` needs to publish command messages at 200Hz. I don't know how to make it stop, which is why I chose to publish empty messages that will crash `MockStationSimulation`.

**Review by hjsuh94 — CHANGES_REQUESTED** [review]
:lgtm: for me!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-:-MYlOe709Gue2LLAI18e:b-wgb6al)* status: 21 of 24 files reviewed, 4 unresolved discussions (waiting on @mpetersen94 and @pangtao22)

___
*[src/plan_runner/send_joint_space_plan.py, line 70 at r3](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYlPWQI0ABMs1MYIvJ9:-MYlPWQI0ABMs1MYIvJA:b-91dqm9) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/c28d33c2274d6398dd81c6e1fb414f6404d2a684/src/plan_runner/send_joint_space_plan.py#L70)):*
> ```Python
> 
> #%% send msg 2 via lcm.
> lc.publish("ROBOT_PLAN", calc_plan_msg(t_knots, q_knots1).encode())
> ```

should be `q_knots2`?
___
*[src/plan_runner/state_machine/plan_manager_state_machine.cc, line 37 at r2](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYl8Hk76Z2ItX4DK7NF:-MYlPCOk4n1PunXHS4Of:bn3rre5) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/fdc722c76b21a3a74105bc8321ec83ae782d6ad1/src/plan_runner/state_machine/plan_manager_state_machine.cc#L37)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

I appreciate moving the error checking to one place.
</blockquote></details>

One question here - if I want to handle errors in the Step function in a way that moves the state machine to ERROR state, does it sound reasonable to purposely set `cmd.q_cmd` to `NaN`?

**Review by hjsuh94 — APPROVED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10)* status: 22 of 24 files reviewed, 4 unresolved discussions (waiting on @mpetersen94 and @pangtao22)

**Review by pangtao22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10)* status: 21 of 24 files reviewed, 4 unresolved discussions (waiting on @hjsuh94 and @mpetersen94)

___
*[src/plan_runner/send_joint_space_plan.py, line 70 at r3](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYlPWQI0ABMs1MYIvJ9:-MYldsuF4gzr9JyLD8Y7:b-896fix) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/c28d33c2274d6398dd81c6e1fb414f6404d2a684/src/plan_runner/send_joint_space_plan.py#L70)):*
<details><summary><i>Previously, hjsuh94 (Hyung Ju Suh (Terry)) wrote…</i></summary><blockquote>

should be `q_knots2`?
</blockquote></details>

Done.
___
*[src/plan_runner/state_machine/plan_manager_state_machine.cc, line 37 at r2](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-MYl8Hk76Z2ItX4DK7NF:-MYldcpM8fUcAQ-NUs-y:ba2y5ji) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/fdc722c76b21a3a74105bc8321ec83ae782d6ad1/src/plan_runner/state_machine/plan_manager_state_machine.cc#L37)):*
<details><summary><i>Previously, hjsuh94 (Hyung Ju Suh (Terry)) wrote…</i></summary><blockquote>

One question here - if I want to handle errors in the Step function in a way that moves the state machine to ERROR state, does it sound reasonable to purposely set `cmd.q_cmd` to `NaN`?
</blockquote></details>

That sounds reasonable to me. We can always change that if we later find that it is not the best thing to do :)

**Review by mpetersen94 — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/10#-:-MYm-FKMExjDqPpTL3Qp:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @hjsuh94 and @mpetersen94)

**Pull request merged**
