### PR TITLE
Add offset frame for trajectory plans

### PR DESCRIPTION
**Pull request by hjsuh94**
1. Implements offsets from `iiwa_link_7` for differential ik. This is useful when we want to do DiffIK on the tool frame, for example. 
2. xyz trajectories are now in `FirstOrderHold` instead of `CubicWithContinuousSecondDerivatives`. The reason is that we would like end effector trajectories to be piecewise linear most of the times and the kinks matter, but the cubic approximation smooths them out. 

@pangtao22 for review please!

FYI: don't forget to call `cmake` to refresh the config file in the build folder.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/34)

### CODE REVIEW

**Review by pangtao22 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/34)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @hjsuh94)

___
*[config/default.yaml, line 16 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/34#-Mcyghly0sVaLkkclD4r:-Mcyghly0sVaLkkclD4s:b-oz13hu) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/99e0b01d28f32136931f8ac0c0981b98d012759c/config/default.yaml#L16)):*
> ```YAML
> robot_ee_body_name: "iiwa_link_7"
> # offset of end-effector frame from iiwa_link_7. Expressed in rpyxyz.
> robot_ee_offset: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
> ```

I think the ee offset should be part of the plan definition, as it can be different for different plans. 
___
*[src/plans/iiwa_plan_factory.cc, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/34#-Mcyda176aur2mCj5yiY:-Mcyda176aur2mCj5yiZ:b-99poi5) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/99e0b01d28f32136931f8ac0c0981b98d012759c/src/plans/iiwa_plan_factory.cc#L37)):*
> ```cpp
>   Eigen::Matrix<double, 6, 1> offset(offset_vec.data());
> 
>   const auto offset_transform = drake::math::RigidTransform<double>(
> ```

We can call this `X_ET`? This is consistent with drake's notation for transforms. E is the end effector frame of the robot. 
___
*[src/plans/iiwa_plan_factory.cc, line 40 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/34#-Mcyd-ZP3MS6mAFhFKEd:-Mcyd-ZQB82kUBCvdtTL:b-oguzpp) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/99e0b01d28f32136931f8ac0c0981b98d012759c/src/plans/iiwa_plan_factory.cc#L40)):*
> ```cpp
>       drake::math::RollPitchYaw<double>(offset.head(3)), offset.tail(3));
> 
>   const auto &frame_T = plant_->AddFrame(
> ```

If we decide to make the offset part of the plan definition, the offset shouldn't be added here. We may need to pass `offset_transform` to the constructor of `TaskSpaceTrajectoryPlan`, and compose `X_WE` and `X_ET` manually there. 
___
*[src/plans/task_space_trajectory_plan.h, line 20 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/34#-McyfdU3CSG1TFb3Tt9E:-McyfdU3CSG1TFb3Tt9F:b-abhz9k) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/72466eb06a941e363a3ba992d8e4dc79766ecdbd/src/plans/task_space_trajectory_plan.h#L20)):*
> ```objc
>       drake::trajectories::PiecewiseQuaternionSlerp<double> quat_traj,
>       drake::trajectories::PiecewisePolynomial<double> xyz_traj,
>       const drake::multibody::MultibodyPlant<double> *plant,
> ```

Why is the const qualifier removed? I don't think the plant needs to be changed inside the plan.
___
*[src/plans/task_space_trajectory_plan.h, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/34#-McyhVmAEtlQuI3WMvwJ:-McyhVmAEtlQuI3WMvwK:b-fjvhy1) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/99e0b01d28f32136931f8ac0c0981b98d012759c/src/plans/task_space_trajectory_plan.h#L21)):*
> ```objc
>       drake::trajectories::PiecewisePolynomial<double> xyz_traj,
>       drake::multibody::MultibodyPlant<double> *plant,
>       const drake::multibody::Frame<double> &frame_E)
> ```

It would be nice to be more consistent about frame names? We can refer to the frame after offset as the tool frame `T`, and use `T` as the symbol for that frame in both IiwaPlanFactory and here.

**Review by pangtao22 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/34)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @hjsuh94)

___
*[src/plans/iiwa_plan_factory.cc, line 40 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/34#-McyiwP08_lhcWxNl5rG:-McyiwP1C1fJplvgeQVU:b-sj36w9) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/99e0b01d28f32136931f8ac0c0981b98d012759c/src/plans/iiwa_plan_factory.cc#L40)):*
> ```cpp
>       drake::math::RollPitchYaw<double>(offset.head(3)), offset.tail(3));
> 
>   const auto &frame_T = plant_->AddFrame(
> ```

If we decide to make the offset part of the plan definition, the offset shouldn't be added to the plant. We may need to pass offset_transform to the constructor of TaskSpaceTrajectoryPlan, and compose X_WE and X_ET manually there.

**Review by hjsuh94 — COMMENTED** [review]
Thanks for the really good comments Pang! This got a bit complicated and I might need to consult on this....

So `DoDifferentialInverseKinematics` requires a frame from a plant, and originally I wanted to add the frame to the plant when the `TaskSpaceTrajectoryPlan` was constructed (hence why `const` was removed since it would make changes to the plant). But this wasn't allowed after `Finalize` (which is done in the constructor of `IiwaPlanFactory`, so I moved adding the frame back to the constructor of `IiwaPlanFactory`.

Currently you are right that the `const` can be restored, but eventually if we want to define a new Frame as part of the plant after we receive the offset from the plan, what would be the right way to do it? Maybe I'm missing some easy way....

1. I think the real right way to do it is to look for a way to write `DoDifferentialInverseKinematics` with an offset argument, but I cannot find an argument for this. 
2. Finalizing the plant after getting the plan seems like a bad idea, especially if plans are coming in online.
3. Make a ControllerPlant for different plans and update the controller plant from the `IiwaPlanFactory`'s plant at every timestep.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/34#-:-MczLJj13ZtIQ9cNlIhX:b-cw4xqx)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @hjsuh94)

**Review by pangtao22 — COMMENTED** [review]
I agree that finalizing the plant outside the constructor of IiwaPlantFactory is a bad idea. But I think there's a way to add the offset without adding frames to MultibodyPlant. One of the interfaces of `DoDifferentialInverseKinematics` takes a user-computed Jacobian, where we can add the offset without adding the frame.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/34#-:-Md0opIBEH-ryXWvE94H:b-kynbqk)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @hjsuh94)

**Review by hjsuh94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/34)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @pangtao22)

___
*[src/plans/iiwa_plan_factory.cc, line 40 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/34#-McyiwP08_lhcWxNl5rG:-Md8Ihrq6BsmyRHUbSRV:b-896fix) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/99e0b01d28f32136931f8ac0c0981b98d012759c/src/plans/iiwa_plan_factory.cc#L40)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

If we decide to make the offset part of the plan definition, the offset shouldn't be added to the plant. We may need to pass offset_transform to the constructor of TaskSpaceTrajectoryPlan, and compose X_WE and X_ET manually there.
</blockquote></details>

Done.
___
*[config/default.yaml, line 16 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/34#-Mcyghly0sVaLkkclD4r:-Md8IkxT4p26WnBztzVY:b-896fix) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/99e0b01d28f32136931f8ac0c0981b98d012759c/config/default.yaml#L16)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

I think the ee offset should be part of the plan definition, as it can be different for different plans. 
</blockquote></details>

Done.

**Review by pangtao22 — COMMENTED** [review]
> Reviewed 7 of 9 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/34)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @hjsuh94)

**Review by pangtao22 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/34#-:-Md8qz1R7nxRy1ns1eW4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hjsuh94)

**Pull request merged**
