### PR TITLE
Package client as a python module. 

### PR DESCRIPTION
**Pull request by hjsuh94**
Package client as a module so we can call them from an external project. Examples of how to do this is included in `examples/zmq_client_example.py`. 

Now the `example` folder contains only examples (as if it was executed outside of plan runner), and all the client code packaged into `plan_runner_client`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/35)

### CODE REVIEW

**Review by hjsuh94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/35)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @pangtao22)

___
*[src/examples/zmq_client_example.py, line 50 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/35#-Md96ima52SvXMZ9tBnc:-Md96ima52SvXMZ9tBnd:bo3hlxp) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/85100ecf1196846c4e81af23b84f78a250498e7d/src/examples/zmq_client_example.py#L50)):*
> ```Python
> #  return FINISHED.
> zmq_client.abort()
> zmq_client.wait_for_plan_to_finish()
> ```

@pangtao22 One question here - if I run the code, `plan_runner` goes into error state with 

'''
terminate called after throwing an instance of 'std::runtime_error'
  what():  AbortAllPlans should not be called in state ERROR
Aborted
'''

Would this be expected behavior? 
___
*[src/examples/zmq_client_example.py, line 75 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/35#-Md96zdZ4xJfSRQLrKbg:-Md96zdZ4xJfSRQLrKbh:birlblf) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/85100ecf1196846c4e81af23b84f78a250498e7d/src/examples/zmq_client_example.py#L75)):*
> ```Python
>     stop_duration = np.random.rand() * duration
>     time.sleep(stop_duration)
>     zmq_client.abort()
> ```

same thing seems to be happening here as above. Do you see this as well?

**Review by hjsuh94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/35)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @pangtao22)

___
*[src/plan_runner_client/calc_plan_msg.py, line 11 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/35#-Md97Rb53t-bdVu608G7:-Md97Rb53t-bdVu608G8:bxogatc) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/85100ecf1196846c4e81af23b84f78a250498e7d/src/plan_runner_client/calc_plan_msg.py#L11)):*
> ```Python
>     msg_plan = lcmt_robot_plan()
> 
>     # It is important that the utime of each plan is unique. The drake
> ```

We discussed briefly about this - you wanted to keep all the `make_??_trajectory_plans` as a separate file, but I think it would be okay to keep all these functions in the same file, and add them as we make more plans?

It would simplify the import lines a lot :)

**Review by pangtao22 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/35)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @hjsuh94)

___
*[README.md, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/35#-MdE5eNZ9jJXvTJw6_En:-MdE5eNZ9jJXvTJw6_Eo:ba90nre) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/85100ecf1196846c4e81af23b84f78a250498e7d/README.md#L17)):*
> ```Markdown
> ```
> 
> To use lcm types defined within plan runner, add the python path:
> ```

It would be nice to properly install this package and import everything from there, but we can leave that for another PR. 
___
*[src/examples/lcm_client_example.py, line 16 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/35#-MdE6JK893C8yWIrffaI:-MdE6JK893C8yWIrffaJ:bdbi3rk) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/85100ecf1196846c4e81af23b84f78a250498e7d/src/examples/lcm_client_example.py#L16)):*
> ```Python
> 
> # This is imported just to query for current joint angles.
> zmq_client = PlanManagerZmqClient()
> ```

The lcm client should be independent of the zmq client. Maybe it's better to access current joint angles through
`iiwa_position_getter.get_iiwa_position_measured()`?
___
*[src/examples/zmq_client_example.py, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/35#-MdE7LTx8xcGWUXliZb4:-MdE7LTx8xcGWUXliZb5:b-6amudd) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/85100ecf1196846c4e81af23b84f78a250498e7d/src/examples/zmq_client_example.py#L24)):*
> ```Python
> #%% Tests joint space plan.
> t_knots = np.array([0, 10])
> q0 = zmq_client.get_current_joint_angles()
> ```

IiwaPositionGetter returns `array(None, dtype=object)` if no IIWA_STATUS has been published yet. The returned q only makes sense when IIWA_STATUS is being published. 
___
*[src/examples/zmq_client_example.py, line 50 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/35#-Md96ima52SvXMZ9tBnc:-MdE8fiWBsVG8HJ6_eO-:blx5hge) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/85100ecf1196846c4e81af23b84f78a250498e7d/src/examples/zmq_client_example.py#L50)):*
<details><summary><i>Previously, hjsuh94 (Hyung Ju Suh (Terry)) wrote…</i></summary><blockquote>

@pangtao22 One question here - if I run the code, `plan_runner` goes into error state with 

'''
terminate called after throwing an instance of 'std::runtime_error'
  what():  AbortAllPlans should not be called in state ERROR
Aborted
'''

Would this be expected behavior? 

</blockquote></details>

These examples are not meant to be run sequentially. Each block separated by #%% should be run with a fresh `MockStationSimulation` at its initial configuration. It may make sense to separate the blocks into individual files.
___
*[src/plan_runner_client/calc_plan_msg.py, line 11 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/35#-Md97Rb53t-bdVu608G7:-MdE8Nes0bVrZxd-e2DA:b-pbdqzg) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/85100ecf1196846c4e81af23b84f78a250498e7d/src/plan_runner_client/calc_plan_msg.py#L11)):*
<details><summary><i>Previously, hjsuh94 (Hyung Ju Suh (Terry)) wrote…</i></summary><blockquote>

We discussed briefly about this - you wanted to keep all the `make_??_trajectory_plans` as a separate file, but I think it would be okay to keep all these functions in the same file, and add them as we make more plans?

It would simplify the import lines a lot :) 
</blockquote></details>

Agreed!

**Review by hjsuh94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/35)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @pangtao22)

___
*[README.md, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/35#-MdE5eNZ9jJXvTJw6_En:-MdHpq8h1ZZ6Tc2HAf7i:bmssd0d) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/85100ecf1196846c4e81af23b84f78a250498e7d/README.md#L17)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

It would be nice to properly install this package and import everything from there, but we can leave that for another PR. 
</blockquote></details>

I saw drake is doing the same thing :) Agree we can do this later! 
___
*[src/examples/lcm_client_example.py, line 16 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/35#-MdE6JK893C8yWIrffaI:-MdHptxO2ooLlOHfpM7C:b-o7vuhc) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/85100ecf1196846c4e81af23b84f78a250498e7d/src/examples/lcm_client_example.py#L16)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

The lcm client should be independent of the zmq client. Maybe it's better to access current joint angles through
`iiwa_position_getter.get_iiwa_position_measured()`?

</blockquote></details>

Good catch! Done.
___
*[src/examples/zmq_client_example.py, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/35#-MdE7LTx8xcGWUXliZb4:-MdHq25GCHgfonkBzCKH:b-8ornig) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/85100ecf1196846c4e81af23b84f78a250498e7d/src/examples/zmq_client_example.py#L24)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

IiwaPositionGetter returns `array(None, dtype=object)` if no IIWA_STATUS has been published yet. The returned q only makes sense when IIWA_STATUS is being published. 
</blockquote></details>

I've raised an exception if no IIWA_STATUS is being published.
___
*[src/examples/zmq_client_example.py, line 50 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/35#-Md96ima52SvXMZ9tBnc:-MdHq5JoBfq7udTACi0Q:b3iklxy) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/85100ecf1196846c4e81af23b84f78a250498e7d/src/examples/zmq_client_example.py#L50)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

These examples are not meant to be run sequentially. Each block separated by #%% should be run with a fresh `MockStationSimulation` at its initial configuration. It may make sense to separate the blocks into individual files.
</blockquote></details>

The tests are now separated by each function and you can choose which one to send via command line argument. I think `test_joint_space_plan_abort`still has the same message but the structure seems much better now.

**Review by pangtao22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/35)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @hjsuh94)

___
*[src/examples/zmq_client_example.py, line 50 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/35#-Md96ima52SvXMZ9tBnc:-MdJL98ZEQAX2jSv-8oG:b-a6pgxj) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/85100ecf1196846c4e81af23b84f78a250498e7d/src/examples/zmq_client_example.py#L50)):*
<details><summary><i>Previously, hjsuh94 (Hyung Ju Suh (Terry)) wrote…</i></summary><blockquote>

The tests are now separated by each function and you can choose which one to send via command line argument. I think `test_joint_space_plan_abort`still has the same message but the structure seems much better now.
</blockquote></details>

Fixed! This function was assuming that `run_joint_space_plan` has already been executed.

**Review by pangtao22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/35)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @hjsuh94)

___
*[src/examples/zmq_client_example.py, line 50 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/35#-Md96ima52SvXMZ9tBnc:-MdJLS-Q64JuzCahFi8r:bby3256) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/85100ecf1196846c4e81af23b84f78a250498e7d/src/examples/zmq_client_example.py#L50)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

Fixed! This function was assuming that `run_joint_space_plan` has already been executed. 
</blockquote></details>

All those errors were triggered because the first q_cmd in the plan is not the same as the robot's current configuration.

**Review by pangtao22 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/35#-:-MdJL_iz-v4exh7fOPH8:bg7igkv)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @hjsuh94)

**Pull request merged**
