### PR TITLE
Mimic ros action

### PR DESCRIPTION
**Pull request by pangtao22**
Changes:
1. client returns immediately after the plan is received by the server.
2. client subscribes to `PLAN_STATUS` channel, and tells if a plan is finished from this channel. 
3. client can preempt a currently-running plan.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24)

### CODE REVIEW

**Comment by pangtao22** [comment]
Known issues:
1. [`client.wait_for_result`](https://github.com/RobotLocomotion/robot-plan-runner/blob/8181182b633faf5e71d883dcd52234c26af9a754/src/examples/joint_space_trajectory_zmq_client.py#L69) may return the result of the previous plan if called right after the previous plan finishes, a problem observed [here](https://github.com/RobotLocomotion/robot-plan-runner/blob/8181182b633faf5e71d883dcd52234c26af9a754/src/examples/joint_space_trajectory_zmq_client.py#L105). The solution is to publish both the plan signature and plan status on `PLAN_STATUS` channel.

**Review by pangtao22 — COMMENTED** [review]
Finally ready for review! +@hjsuh94 +@mpetersen94 
A nice place to start is to run `src/examples/joint_space_trajectory_zmq_client.py`. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-:-MZng6017CxkXEahE1l3:bvkkw8)* status: 0 of 22 files reviewed, 1 unresolved discussion (waiting on @hjsuh94 and @mpetersen94)

___
*[src/sandbox.cc, line 1 at r3](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-MZngfvDCRbePjObKqoj:-MZngfvDCRbePjObKqok:biuhv0d) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/9a885570f70897b7e78c1677d33a9f4167c79681/src/sandbox.cc#L1)):*
> ```cpp
> #include <Eigen/Dense>
> ```

I shouldn't commit sandbox files, but deleting the corresponding lines from CMakeList.txt every commit is also a hassle. Is there a nicer way to exclude sandbox files?

**Review by hjsuh94 — COMMENTED** [review]
:lgtm: for me.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-:-MZon4szCNeKSvBFjU7M:b-wgb6a8)* status: 0 of 22 files reviewed, 4 unresolved discussions (waiting on @hjsuh94, @mpetersen94, and @pangtao22)

___
*[src/iiwa_plan_manager.cc, line 81 at r4](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-MZnxMFq5TZAYFFkEEJO:-MZnxMFrCojmaIcxc_Sr:b20e4st) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/474604f4e8d309f4dc583c09c7239fc8ea349e56/src/iiwa_plan_manager.cc#L81)):*
> ```cpp
>                                .count();
>     state_machine_->PrintCurrentState(t_now_seconds);
>     std::this_thread::sleep_until(next_start_time);
> ```

Just out of curiosity, any explanation for the change of code here? 
___
*[src/iiwa_plan_manager.cc, line 122 at r4](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-MZnyzEM5Utd8tMJUNeQ:-MZnyzEM5Utd8tMJUNeR:b-45dxb1) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/474604f4e8d309f4dc583c09c7239fc8ea349e56/src/iiwa_plan_manager.cc#L122)):*
> ```cpp
>     // Blocks until a plan msg is received.
>     auto res = plan_server.recv(plan_msg, zmq::recv_flags::none);
>     DRAKE_THROW_UNLESS(res.has_value());
> ```

Just confirming, but all the calls to `DRAKE_THROW_UNLESS` are not expected to happen during operation? (i.e. more like an assert sanity check for the code rather than an actual exception?) 
___
*[src/examples/joint_space_trajectory_lcm_client.py, line 11 at r4](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-MZomCFYEyk4HPtPLEzM:-MZomCFYEyk4HPtPLEzN:b2rzxr2) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/474604f4e8d309f4dc583c09c7239fc8ea349e56/src/examples/joint_space_trajectory_lcm_client.py#L11)):*
> ```Python
> 
> #%% send msg 2 via lcm.
> lc.publish("ROBOT_PLAN", calc_plan_msg(t_knots, q_knots2).encode())
> ```

This script doesn't seem to do anything for plan runner (which is expected since plan runner runs on zmq). I suppose this is only for the system version?
___
*[src/examples/joint_space_trajectory_zmq_client.py, line 104 at r4](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-MZonyfYBncTf_sNpl4L:-MZonyfYBncTf_sNpl4M:bx2zgvo) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/474604f4e8d309f4dc583c09c7239fc8ea349e56/src/examples/joint_space_trajectory_zmq_client.py#L104)):*
> ```Python
> 
> 
> zmq_client = PlanManagerZmqClient()
> ```

I really like this interface, and I think most people will be using the exact same class for the client. 

IMO we should get this out of `examples` and make it a part of `robot-plan-runner` python package, so that external python scripts can import this and just write what we have below this line. We might even write an interface for creating joint_space / task_space plans. 

But I'm happy to do this on a separate PR.

**Review by pangtao22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24)* status: 0 of 22 files reviewed, 4 unresolved discussions (waiting on @hjsuh94 and @mpetersen94)

___
*[src/iiwa_plan_manager.cc, line 81 at r4](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-MZnxMFq5TZAYFFkEEJO:-MZpHGuO68WKqxy0TwKK:bd46l4v) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/474604f4e8d309f4dc583c09c7239fc8ea349e56/src/iiwa_plan_manager.cc#L81)):*
<details><summary><i>Previously, hjsuh94 (Hyung Ju Suh (Terry)) wrote…</i></summary><blockquote>

Just out of curiosity, any explanation for the change of code here? 
</blockquote></details>

The change was inspired by [this blog post](https://bulldozer00.blog/2013/12/27/periodic-processing-with-standard-c11-facilities/). The TLDR version is that using `sleep_until` instead of `sleep_for` accounts for the time taken to execute the code from the start of the loop until the sleep command. But in practice it takes less than 1e-4 seconds to print in this thread, but the accuracy of sleep functions seems to be on the order of milliseconds.
___
*[src/iiwa_plan_manager.cc, line 122 at r4](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-MZnyzEM5Utd8tMJUNeQ:-MZpJWCl8xgg9-JSiFqH:bd2abxe) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/474604f4e8d309f4dc583c09c7239fc8ea349e56/src/iiwa_plan_manager.cc#L122)):*
<details><summary><i>Previously, hjsuh94 (Hyung Ju Suh (Terry)) wrote…</i></summary><blockquote>

Just confirming, but all the calls to `DRAKE_THROW_UNLESS` are not expected to happen during operation? (i.e. more like an assert sanity check for the code rather than an actual exception?) 
</blockquote></details>

After checking ZMQ's docs, it seems that the throw might happen only if the recv or send_flags are set to `dontwait`, which is not what we're doing here. Will remove. 
___
*[src/examples/joint_space_trajectory_lcm_client.py, line 11 at r4](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-MZomCFYEyk4HPtPLEzM:-MZpKKPH0SDnxQQoPBxW:bpx6zjr) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/474604f4e8d309f4dc583c09c7239fc8ea349e56/src/examples/joint_space_trajectory_lcm_client.py#L11)):*
<details><summary><i>Previously, hjsuh94 (Hyung Ju Suh (Terry)) wrote…</i></summary><blockquote>

This script doesn't seem to do anything for plan runner (which is expected since plan runner runs on zmq). I suppose this is only for the system version?
</blockquote></details>

Yes! I'll add some comments to make it clear. 
___
*[src/examples/joint_space_trajectory_zmq_client.py, line 104 at r4](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-MZonyfYBncTf_sNpl4L:-MZpKQ1ZCzbxRTmBO-Yq:bryvw79) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/474604f4e8d309f4dc583c09c7239fc8ea349e56/src/examples/joint_space_trajectory_zmq_client.py#L104)):*
<details><summary><i>Previously, hjsuh94 (Hyung Ju Suh (Terry)) wrote…</i></summary><blockquote>

I really like this interface, and I think most people will be using the exact same class for the client. 

IMO we should get this out of `examples` and make it a part of `robot-plan-runner` python package, so that external python scripts can import this and just write what we have below this line. We might even write an interface for creating joint_space / task_space plans. 

But I'm happy to do this on a separate PR. 
</blockquote></details>

Will add to the TODO list in #21

**Review by mpetersen94 — CHANGES_REQUESTED** [review]
:lgtm: with some comments

> Reviewed 8 of 15 files at r1, 1 of 5 files at r2, 8 of 10 files at r3, 1 of 2 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-:-M_MioUNCNQQuzuvSviK:b-wkd30r)* status: 22 of 23 files reviewed, 5 unresolved discussions (waiting on @hjsuh94, @mpetersen94, and @pangtao22)

___
*[src/iiwa_plan_manager.cc, line 81 at r4](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-MZnxMFq5TZAYFFkEEJO:-M_M_0yUDONVWAyHHGic:b-h6rupg) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/474604f4e8d309f4dc583c09c7239fc8ea349e56/src/iiwa_plan_manager.cc#L81)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

The change was inspired by [this blog post](https://bulldozer00.blog/2013/12/27/periodic-processing-with-standard-c11-facilities/). The TLDR version is that using `sleep_until` instead of `sleep_for` accounts for the time taken to execute the code from the start of the loop until the sleep command. But in practice it takes less than 1e-4 seconds to print in this thread, but the accuracy of sleep functions seems to be on the order of milliseconds.
</blockquote></details>

I'm fine with any version of this.  Given that this just prints out the state machine's status for user debugging purposes, I'm not sure how much jitter on the order of milliseconds matters.  
___
*[src/iiwa_plan_manager.cc, line 122 at r5](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-M_Mbyu2EQ2gJuIWFQDE:-M_Mbyu2EQ2gJuIWFQDF:b-9wxbvm) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/be1e525d2a6f4c44fe552aeea0b26f5c7fde7b7f/src/iiwa_plan_manager.cc#L122)):*
> ```cpp
>     // Blocks until a plan msg is received.
>     auto res = plan_server.recv(plan_msg, zmq::recv_flags::none);
>     res = plan_server.send(zmq::str_buffer("plan_received"),
> ```

Can you move this after the plan is queue'd that way we only respond that the plan was received after we've done any checks we want to do on it.
___
*[src/iiwa_plan_manager.cc, line 153 at r5](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-M_McTUL9gNcvBRRUiMY:-M_McTUL9gNcvBRRUiMZ:btfyebc) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/be1e525d2a6f4c44fe552aeea0b26f5c7fde7b7f/src/iiwa_plan_manager.cc#L153)):*
> ```cpp
>         //  distinguished, both are designated "FINISHED".
>         //  On the other hand, if the client calls abort, it should know that
>         //  the plan doesn't finish normally?
> ```

Is there any world where we'd have one process sending a plan and another process checking something and aborting plans if there is a problem?
___
*[src/iiwa_plan_manager.cc, line 171 at r5](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-M_Md9aP5hEMnrf4kT7r:-M_Md9aQ6cYfiJhVOXaT:b-92wbt1) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/be1e525d2a6f4c44fe552aeea0b26f5c7fde7b7f/src/iiwa_plan_manager.cc#L171)):*
> ```cpp
>       status_publisher.send(reply, zmq::send_flags::none);
> 
>       if (current_state != PlanManagerStateTypes::kStateRunning) {
> ```

Does it make sense to make this the condition of the while loop instead of doing a while(true) and a break statement?
___
*[src/sandbox.cc, line 1 at r3](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-MZngfvDCRbePjObKqoj:-M_MiP0xDNJW3PPOXYU4:bq6aytr) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/9a885570f70897b7e78c1677d33a9f4167c79681/src/sandbox.cc#L1)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

I shouldn't commit sandbox files, but deleting the corresponding lines from CMakeList.txt every commit is also a hassle. Is there a nicer way to exclude sandbox files?
</blockquote></details>

You could try moving sandbox files into a sandbox folder (which is already in .gitignore) and adding this at the top level:
```
if(IS_DIRECTORY "{CMAKE_CURRENT_SOURCE_DIR}/sandbox")
    add_subdirectory(sandbox)
endif()
```
___
*[src/examples/joint_space_trajectory_lcm_client.py, line 2 at r5](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-M_Me0qxCwi8Nre86-E7:-M_Me0qxCwi8Nre86-E8:bekmx70) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/be1e525d2a6f4c44fe552aeea0b26f5c7fde7b7f/src/examples/joint_space_trajectory_lcm_client.py#L2)):*
> ```Python
> import lcm
> from make_joint_space_trajectory_plan import *
> ```

What's the rationale for splitting up these two files?

**Review by pangtao22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24)* status: 19 of 24 files reviewed, 4 unresolved discussions (waiting on @hjsuh94 and @mpetersen94)

___
*[src/iiwa_plan_manager.cc, line 122 at r5](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-M_Mbyu2EQ2gJuIWFQDE:-M_S9Z5Z5JkrF0pRQjT5:b-6mr9n9) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/be1e525d2a6f4c44fe552aeea0b26f5c7fde7b7f/src/iiwa_plan_manager.cc#L122)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Can you move this after the plan is queue'd that way we only respond that the plan was received after we've done any checks we want to do on it.
</blockquote></details>

Done! Also adds a TODO for sending back to the client whether the plan is added successfully or not. 
___
*[src/iiwa_plan_manager.cc, line 153 at r5](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-M_McTUL9gNcvBRRUiMY:-M_S5BIw0V_wK9-SAvrW:biebv2r) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/be1e525d2a6f4c44fe552aeea0b26f5c7fde7b7f/src/iiwa_plan_manager.cc#L153)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Is there any world where we'd have one process sending a plan and another process checking something and aborting plans if there is a problem?
</blockquote></details>

That sounds like a totally plausible scenario. There are multiple ways to implement publishing how the plan finishes. They are compatible with the current implementation. We can pick one if the use case arises. 
___
*[src/iiwa_plan_manager.cc, line 171 at r5](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-M_Md9aP5hEMnrf4kT7r:-M_S4jI6EhfYrVI84ohm:bcg01tu) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/be1e525d2a6f4c44fe552aeea0b26f5c7fde7b7f/src/iiwa_plan_manager.cc#L171)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Does it make sense to make this the condition of the while loop instead of doing a while(true) and a break statement?
</blockquote></details>

The reply message (in the line above) would not be sent if this condition was checked at the beginning of the while loop. 
___
*[src/sandbox.cc, line 1 at r3](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-MZngfvDCRbePjObKqoj:-M_SIJxX1XRPjDRvaTpc:b-hay2ib) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/9a885570f70897b7e78c1677d33a9f4167c79681/src/sandbox.cc#L1)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

You could try moving sandbox files into a sandbox folder (which is already in .gitignore) and adding this at the top level:
```
if(IS_DIRECTORY "{CMAKE_CURRENT_SOURCE_DIR}/sandbox")
    add_subdirectory(sandbox)
endif()
```
</blockquote></details>

Thanks! 
___
*[src/examples/joint_space_trajectory_lcm_client.py, line 2 at r5](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/24#-M_Me0qxCwi8Nre86-E7:-M_S2W-y1OXsJOgBlGka:b-oc4oe) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/be1e525d2a6f4c44fe552aeea0b26f5c7fde7b7f/src/examples/joint_space_trajectory_lcm_client.py#L2)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

What's the rationale for splitting up these two files?
</blockquote></details>

The ZMQ client supports all ROS action features and already has a well-defined interface. The next step is perhaps to make that interface more permanent by porting tp C++ and writing python bindings? In contrast, the Lcm client only supports sending plans. It doesn't update plan status or allows the user to abort.

**Pull request merged**
