### PR TITLE
Build structure cleaning

### PR DESCRIPTION
**Pull request by hjsuh94**
PR includes 3 changes.
1. Miscellaneous changes to README for more instructions.
2. Exposes binaries and libraries into bin / lib. 
3. Changes to folder structure to get rid of existing examples in `drake-external-examples.`

It looks like a lot but the changes are pretty minimal. Let me know if a short explanation is required! 

@pangtao22 I'm also fine with rebasing this on #10 after it gets merged! 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/11)

### CODE REVIEW

**Review by mpetersen94 — APPROVED** [review]
Thank you for this clean up! :lgtm_strong: 

> Reviewed 50 of 50 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/11#-:-MYeizmn9jElQCukBhVe:b-hhl2r6)* status: all files reviewed, 1 unresolved discussion (waiting on @hjsuh94 and @pangtao22)

___
*[src/CMakeLists.txt, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/11#-MYej6TZBspJCF2CiQ2Z:-MYej6TZBspJCF2CiQ2_:b1clsqj) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/2780cf26914487627b9f81774eb46f4c554dbcb4/src/CMakeLists.txt#L18)):*
> ```CMake
> target_link_libraries(run_plan_manager iiwa_plan_manager)
> 
> add_test(NAME import_all_test COMMAND
> ```

Does it makes sense to keep this test?  We don't have any python code in this repo.

**Review by hjsuh94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/11)* status: all files reviewed, 1 unresolved discussion (waiting on @mpetersen94 and @pangtao22)

___
*[src/CMakeLists.txt, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/11#-MYej6TZBspJCF2CiQ2Z:-MYem4L1EvzUIySwUvhZ:b-qjs488) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/2780cf26914487627b9f81774eb46f4c554dbcb4/src/CMakeLists.txt#L18)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Does it makes sense to keep this test?  We don't have any python code in this repo.
</blockquote></details>

We soon will when it comes to writing test code and clients :)

**Review by pangtao22 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/11)* status: all files reviewed, 2 unresolved discussions (waiting on @hjsuh94 and @mpetersen94)

___
*[CMakeLists.txt, line 77 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/11#-MYgkICnEzwL56VugOC3:-MYgkICnEzwL56VugOC4:bdf9m4k) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/2780cf26914487627b9f81774eb46f4c554dbcb4/CMakeLists.txt#L77)):*
> ```CMake
> set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
> set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
> set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
> ```

Sorry that I'm not an cmake expert. Could you briefly explain what these do? Thanks!

**Review by hjsuh94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/11)* status: all files reviewed, 2 unresolved discussions (waiting on @mpetersen94 and @pangtao22)

___
*[CMakeLists.txt, line 77 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/11#-MYgkICnEzwL56VugOC3:-MYgmWr69d66vgZhg-2f:b-mzvc77) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/2780cf26914487627b9f81774eb46f4c554dbcb4/CMakeLists.txt#L77)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

Sorry that I'm not an cmake expert. Could you briefly explain what these do? Thanks!
</blockquote></details>

you are way more experienced than me ;)  

these lines will simply add a `bin` folder in your build directory and put all the executables there. (And all the `.a` files in the `lib` file)

**Review by pangtao22 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/11)* status: all files reviewed, 1 unresolved discussion (waiting on @mpetersen94)

**Review by mpetersen94 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hjsuh94)

**Comment by mpetersen94** [comment]
@hjsuh94 Are you ok with me merging this?

**Comment by hjsuh94** [comment]
Waiting on #10!

**Review by pangtao22 — APPROVED** [review]
LGTM!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/11#-:-MYlgToY2pHn1WSHFlua:b-85i648)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hjsuh94)

**Review by pangtao22 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/11#-:-MYlgro01PW8OeDu6uqJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hjsuh94)

**Pull request merged**
