### PR TITLE
Add SchunkManager

### LINKED ISSUE #5: Implement Schunk into plan_runner

### PR DESCRIPTION
**Pull request by hjsuh94**
- Adds simple schunk manager to the client. 
- Adds a basic hardware testing script.

Closes #5 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/37)

### CODE REVIEW

**Review by pangtao22 — CHANGES_REQUESTED** [review]
Sorry that I just saw this! 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/37#-:-Mg0-iVp71diGr_hCamk:bwgrwzk)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @hjsuh94)

___
*[src/plan_runner_client/zmq_client.py, line 159 at r3](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/37#-Mg-z3OW9bSiElkAHs0g:-Mg-z3OW9bSiElkAHs0h:b-p0dfq4) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/996061336504826b8d308a8944b378055d3f99b0/src/plan_runner_client/zmq_client.py#L159)):*
> ```Python
>     def sub_callback(self, channel, data):
>         schunk_status_msg = lcmt_schunk_wsg_status.decode(data)
>         self.schunk_position_measured = schunk_status_msg.actual_position_mm
> ```

Do we need to lock `self.schunk_position_measured` when writing to it? For most objects I think a lock is necessary, but here it's just a float so it's probably fine without the lock?

**Review by pangtao22 — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/37)* status: all files reviewed, 1 unresolved discussion (waiting on @hjsuh94)

**Review by hjsuh94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/37)* status: all files reviewed, 1 unresolved discussion (waiting on @pangtao22)

___
*[src/plan_runner_client/zmq_client.py, line 159 at r3](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/37#-Mg-z3OW9bSiElkAHs0g:-Mg3QXk330nTqLAPjdTh:bqdog4r) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/996061336504826b8d308a8944b378055d3f99b0/src/plan_runner_client/zmq_client.py#L159)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

Do we need to lock `self.schunk_position_measured` when writing to it? For most objects I think a lock is necessary, but here it's just a float so it's probably fine without the lock?
</blockquote></details>

I took it from the `IiwaPositionGetter` pattern, but I think it's fine either way. Would you recommend that we remove it?

**Review by pangtao22 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/37)* status: all files reviewed, 1 unresolved discussion (waiting on @hjsuh94)

___
*[src/plan_runner_client/zmq_client.py, line 159 at r3](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/37#-Mg-z3OW9bSiElkAHs0g:-Mg45-hOD983IHd1IV-I:b-3coat) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/996061336504826b8d308a8944b378055d3f99b0/src/plan_runner_client/zmq_client.py#L159)):*
<details><summary><i>Previously, hjsuh94 (Hyung Ju Suh (Terry)) wrote…</i></summary><blockquote>

I took it from the `IiwaPositionGetter` pattern, but I think it's fine either way. Would you recommend that we remove it?  
</blockquote></details>

Ahhh... I think it was an oversight that writing to `self.iiwa_status` is not lock-protected in  `IiwaPositionGetter`. Would you mind adding locks around writing to these fields, following the pattern here: https://github.com/RobotLocomotion/robot-plan-runner/blob/138741554291b87f79aecdf640d118f9cbf30673/src/plan_runner_client/zmq_client.py#L96-L98 ?

**Review by pangtao22 — COMMENTED** [review]
:lgtm: Added locks to protect multi-threaded subscription and fixed some bugs. Please take another look!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/37#-:-Mg7X5_a-E5hz1LseYez:b-9aegxt)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @hjsuh94 and @pangtao22)

**Review by hjsuh94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/37)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @pangtao22)

___
*[src/plan_runner_client/zmq_client.py, line 159 at r3](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/37#-Mg-z3OW9bSiElkAHs0g:-Mg7fAku63M10KvrkFSO:b-u50399) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/996061336504826b8d308a8944b378055d3f99b0/src/plan_runner_client/zmq_client.py#L159)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

Ahhh... I think it was an oversight that writing to `self.iiwa_status` is not lock-protected in  `IiwaPositionGetter`. Would you mind adding locks around writing to these fields, following the pattern here: https://github.com/RobotLocomotion/robot-plan-runner/blob/138741554291b87f79aecdf640d118f9cbf30673/src/plan_runner_client/zmq_client.py#L96-L98 ?
</blockquote></details>

Oops sorry - I should have done this sooner but got busy with sysid! LGTM for me!

**Pull request merged**
