### PR TITLE
Resolve iiwa command delay when using Drake systems

### PR DESCRIPTION
**Pull request by pangtao22**
Implement the lcm-driven loop idea discussed in #29 .

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/32)

### CODE REVIEW

**Review by pangtao22 — COMMENTED** [review]
+@hjsuh94 for review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/32#-:-McWUvLi0_W6QUbBGakH:b-rpas8s)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @hjsuh94)

___
*[src/lcm_delay_analysis.py, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/32#-McWV-LA-e-DZCcNsEnO:-McWV-LA-e-DZCcNsEnP:b303b9) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/7bdd5586af77dde541477a584e05f0ee74e8deb9/src/lcm_delay_analysis.py#L1)):*
> ```Python
> #%%
> ```

This is used to generate the plots in #29, but I'm not sure if this script should be kept in this repo.

**Review by hjsuh94 — APPROVED** [review]
:lgtm: for me based on the experiments in #29! 

one question - I wonder if this closes #30 as well? All the systems-based code repo seem to be using `drake::lcm`. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/32#-:-Mc_DAK5-Nxp1TFGGd0N:bchu93t)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @hjsuh94 and @pangtao22)

___
*[src/lcm_delay_analysis.py, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/32#-McWV-LA-e-DZCcNsEnO:-Mc_C2vy9xmNJznBUbts:bxcfz2) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/7bdd5586af77dde541477a584e05f0ee74e8deb9/src/lcm_delay_analysis.py#L1)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

This is used to generate the plots in #29, but I'm not sure if this script should be kept in this repo. 
</blockquote></details>

I run into this kind of problem a lot too, and wonder if there is a better solution :sweat: 

I think it's okay to keep this in the repo, even if it's for our own record. But maybe we can isolate them in a separate folder? 
___
*[src/plan_manager_system/iiwa_plan_manager_hardware_interface.cc, line 38 at r2](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/32#-Mc_Bh1p8C7j10xd6ici:-Mc_Bh1p8C7j10xd6icj:b-ong6o5) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/f16dfc1362202f4ed4a922ef80b921c3db055c82/src/plan_manager_system/iiwa_plan_manager_hardware_interface.cc#L38)):*
> ```cpp
>   // Wait for the first IIWA_STATUS message.
>   drake::log()->info("Waiting for first lcmt_iiwa_status");
>   drake::lcm::LcmHandleSubscriptionsUntil(
> ```

The logic here is clear from the pseudocode in the issue - nice documentation!

**Comment by pangtao22** [comment]
I should have included more details in that repo :) I was referring to replacing [this lcm subscription](https://github.com/RobotLocomotion/robot-plan-runner/blob/dd939df2396dcf83e13dd90114bfde8b7ffafaeb/src/iiwa_plan_manager.cc#L54-L56) with DrakeLcm, so that we can properly throw exceptions in the callback, and run unit tests with mock lcm.

**Review by pangtao22 — COMMENTED** [review]
> Dismissed @hjsuh94 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/32)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @hjsuh94)

___
*[src/plan_manager_system/iiwa_plan_manager_hardware_interface.cc, line 38 at r2](https://reviewable.io/reviews/robotlocomotion/robot-plan-runner/32#-Mc_Bh1p8C7j10xd6ici:-McaP8uY0DYN52tBjCO9:b-896fix) ([raw file](https://github.com/robotlocomotion/robot-plan-runner/blob/f16dfc1362202f4ed4a922ef80b921c3db055c82/src/plan_manager_system/iiwa_plan_manager_hardware_interface.cc#L38)):*
<details><summary><i>Previously, hjsuh94 (Hyung Ju Suh (Terry)) wrote…</i></summary><blockquote>

The logic here is clear from the pseudocode in the issue - nice documentation! 
</blockquote></details>

Done.

**Pull request merged**
